/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateEquationArgs = IDL.Record({
  'canvasData' : IDL.Text,
  'name' : IDL.Text,
});
export const EquationId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Equation = IDL.Record({
  'id' : EquationId,
  'canvasData' : IDL.Text,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const UpdateEquationArgs = IDL.Record({
  'id' : EquationId,
  'canvasData' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createEquation' : IDL.Func([CreateEquationArgs], [Equation], []),
  'deleteEquation' : IDL.Func([EquationId], [IDL.Bool], []),
  'getEquation' : IDL.Func([EquationId], [IDL.Opt(Equation)], ['query']),
  'listEquations' : IDL.Func([], [IDL.Vec(Equation)], ['query']),
  'updateEquation' : IDL.Func([UpdateEquationArgs], [IDL.Opt(Equation)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateEquationArgs = IDL.Record({
    'canvasData' : IDL.Text,
    'name' : IDL.Text,
  });
  const EquationId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Equation = IDL.Record({
    'id' : EquationId,
    'canvasData' : IDL.Text,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const UpdateEquationArgs = IDL.Record({
    'id' : EquationId,
    'canvasData' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createEquation' : IDL.Func([CreateEquationArgs], [Equation], []),
    'deleteEquation' : IDL.Func([EquationId], [IDL.Bool], []),
    'getEquation' : IDL.Func([EquationId], [IDL.Opt(Equation)], ['query']),
    'listEquations' : IDL.Func([], [IDL.Vec(Equation)], ['query']),
    'updateEquation' : IDL.Func([UpdateEquationArgs], [IDL.Opt(Equation)], []),
  });
};

export const init = ({ IDL }) => { return []; };