/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateEquationArgs { 'canvasData' : string, 'name' : string }
export interface Equation {
  'id' : EquationId,
  'canvasData' : string,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type EquationId = bigint;
export type Timestamp = bigint;
export interface UpdateEquationArgs {
  'id' : EquationId,
  'canvasData' : [] | [string],
  'name' : [] | [string],
}
export type UserId = Principal;
export interface _SERVICE {
  'createEquation' : ActorMethod<[CreateEquationArgs], Equation>,
  'deleteEquation' : ActorMethod<[EquationId], boolean>,
  'getEquation' : ActorMethod<[EquationId], [] | [Equation]>,
  'listEquations' : ActorMethod<[], Array<Equation>>,
  'updateEquation' : ActorMethod<[UpdateEquationArgs], [] | [Equation]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];